class MessageTextResponse:
    USER_IS_REGISTERED_MESSAGE = "Пользователь зарегистрирован!"
    OOPS_MESSAGE = "Что-то пошло не так..."
    ADD_OR_DELETE_MESSAGE = "Управление маствотчами:"
    USER_IS_NOT_REGISTERED_MESSAGE = "Чтобы пользоваться ботом, вам нужно зарегистрироваться!"
    NO_RATED_MUSTWATCHES_MESSAGE = "В этой группе пока никто не оценил маствотчи..."
    CHOOSE_USER_TO_ADD_MESSAGE = "Кому добавить маствотч?"
    CHOOSE_MUSTWATCH_TO_DELETE_MESSAGE = "Выберите маствотч, чтобы полностью удалить его из группы:"
    NO_MORE_MUSTWATCHES_TO_DELETE_MESSAGE = "Пока никто не добавил маствотчи, чтобы их удалить..."
    CHOOSE_MUSTWATCH_TO_RATE_MESSAGE = "Нажмите на маствотч, чтобы поставить ему оценку:"
    NO_MORE_MUSTWATCHES_TO_RATE_MESSAGE = "Вы уже посмотрели все назначенные вам маствотчи..."
    ADD_OR_CHOOSE_MUSTWATCH_MESSAGE = "Список маствотчей, которые можно добавить:"
    NO_MORE_MUSTWATCHES_TO_ADD = "Больше нет маствотчей, которые можно было бы добавить выбранному пользователю(ям)..."
    CHOOSE_ONE_USER_MESSAGE = "Выберите пользователя:"
    NO_OTHER_USERS_REGISTERED_MESSAGE = "В этой группе пока никто не зарегистрировался..."
    RATE_MUSTWATCH_MESSAGE = "Оцените маствотч:"
    SEND_ITEM_TITLE_MESSAGE = "Отправьте название маствотча:"
    END_MESSAGE = "Сделано!"
